services:

  postgres:
    image: postgres:16
    container_name: pedeai-postgres
    environment:
      POSTGRES_USER: pedeai
      POSTGRES_PASSWORD: pedeai123
      POSTGRES_DB: pedeai_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: pedeai-backend
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://pedeai:pedeai123@postgres:5432/pedeai_db